### ISSUE TITLE
Edlib development environment issues

### ISSUE THREAD

**Issue by chrieinv** [cerpus/Edlib#2331]
## Auth API
Config missing in `./localSetup/.env.example`
```
EDLIBCOMMON_EXTERNALAUTH_ADAPTER=cerpusAuth
EDLIBCOMMON_EXTERNALAUTH_ISSUER=https://auth.local/
EDLIBCOMMON_EXTERNALAUTH_ADAPTER_CERPUSAUTH_URL=https://auth.local
EDLIBCOMMON_EXTERNALAUTH_ADAPTER_CERPUSAUTH_CLIENTID=testClient
EDLIBCOMMON_EXTERNALAUTH_ADAPTER_CERPUSAUTH_SECRET=verySecret
```

## Content Author
Content Author build fails with `permission denied`
```
edlib-contentauthor-watch-1  | Compiling Mix
edlib-contentauthor-watch-1  | node:internal/fs/utils:347
edlib-contentauthor-watch-1  |     throw err;
edlib-contentauthor-watch-1  |     ^
edlib-contentauthor-watch-1  |
edlib-contentauthor-watch-1  | Error: EACCES: permission denied, open '/app/public/mix-manifest.json'
edlib-contentauthor-watch-1  |     at Object.openSync (node:fs:590:3)
edlib-contentauthor-watch-1  |     at Object.writeFileSync (node:fs:2202:35)
edlib-contentauthor-watch-1  |     at File.write (/app/node_modules/laravel-mix/src/File.js:211:12)
edlib-contentauthor-watch-1  |     at Manifest.refresh (/app/node_modules/laravel-mix/src/Manifest.js:86:50)
edlib-contentauthor-watch-1  |     at /app/node_modules/laravel-mix/src/webpackPlugins/ManifestPlugin.js:21:48
edlib-contentauthor-watch-1  |     at Hook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
edlib-contentauthor-watch-1  |     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/app/node_modules/tapable/lib/Hook.js:18:14)
edlib-contentauthor-watch-1  |     at Compiler.emitAssets (/app/node_modules/webpack/lib/Compiler.js:873:19)
edlib-contentauthor-watch-1  |     at /app/node_modules/webpack/lib/Watching.js:167:21
edlib-contentauthor-watch-1  |     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
edlib-contentauthor-watch-1  |   errno: -13,
edlib-contentauthor-watch-1  |   syscall: 'open',
edlib-contentauthor-watch-1  |   code: 'EACCES',
edlib-contentauthor-watch-1  |   path: '/app/public/mix-manifest.json'
edlib-contentauthor-watch-1  | }
```

**Comment by emmachughes** [comment]
@chrieinv I cannot reproduce the 'permission denied' issue. How do you have Docker set up?

**Comment by chrieinv** [comment]
I followed the instructions on https://docs.docker.com/engine/install/ubuntu/ for Docker.
Then installed Compose using https://docs.docker.com/compose/install/linux/
And the post-install step to use Docker as a non-root user (https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)

I have the same issue in my current dev-env, if I edit a js file `conthentauthor-watch` crashes. If I restart the container it builds without any errors, then crashes next time a js file is edited.
```
 [webpack-cli] [Error: EACCES: permission denied, open '/app/public/fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.eot'] {
   errno: -13,
   code: 'EACCES',
   syscall: 'open',
   path: '/app/public/fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.eot'
 }
```

If I look at the folders `public` and `vendor` are owned by user and group `82`. In `contentauthor-fpm` this is user and group `www-data`. In `contentauthor-watch` this is user `82` and group `www-data`
